"""users phone number

Revision ID: d4b296fd90b2
Revises: 93f32d51bab4
Create Date: 2024-10-10 13:14:47.302899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4b296fd90b2'
down_revision: Union[str, None] = '93f32d51bab4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.String(), nullable=False)), sa.Column('phone_number', sa.Integer(), nullable=True)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number', 'name')

    # ### end Alembic commands ###
